allowBuilds:
  esbuild: true

packages:
  # Applications
  - "apps/ferride"

  # Internal configuration packages
  - "packages/eslint"
  - "packages/tailwindcss"
  - "packages/tsconfig"

catalog:
  eslint: ^10.6.0
  knip: ^6.24.0
  prettier: ^3.9.4
  typescript: ~5.8.3
  vite: ^7.0.4

catalogs:
  react:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
  tailwindcss:
    "@tailwindcss/vite": ^4.3.2
    tailwindcss: ^4.3.2
  tauri:
    "@tauri-apps/api": ^2
    "@tauri-apps/cli": "^2"
