name: Build

on:
  # push:
  #   branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache Turbo Outputs
        uses: actions/cache@v6
        with:
          path: "**/.turbo"
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11.10
          cache: true

      - name: Install Node
        uses: actions/setup-node@v6

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc, wasm32-unknown-unknown

      - name: Cache Rust Outputs
        uses: Swatinem/rust-cache@v2

      - name: Install Wasm-Pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Install Web Dependencies
        run: pnpm ci

      - name: Install Tauri Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          libwebkit2gtk-4.1-0=2.44.0-2 \
          libwebkit2gtk-4.1-dev=2.44.0-2 \
          libjavascriptcoregtk-4.1-0=2.44.0-2 \
          libjavascriptcoregtk-4.1-dev=2.44.0-2 \
          gir1.2-javascriptcoregtk-4.1=2.44.0-2 \
          gir1.2-webkit2-4.1=2.44.0-2 \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          xdg-utils \
          clang \
          nsis \
          llvm \
          lld
          cargo install --locked cargo-xwin

      - name: Build Tauri App
        run: pnpm build --affected

      - name: Move Build Artifacts
        run: |
          mkdir -p ./build
          mv ./target/release/bundle/appimage/*.AppImage ./build
          mv ./target/release/bundle/deb/*.deb ./build
          mv ./target/release/bundle/rpm/*.rpm ./build
          mv ./target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe ./build
          mv ./target/x86_64-pc-windows-msvc/release/*.exe ./build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: tauri-artifacts
          path: ./build
